#!/bin/bash

shopt -s expand_aliases

object() {
    local identifier=$1
    shift
    if [ "${1:0:1}" == '.' ]; then
        local property="${identifier}_props[${1:1}]"
        if [ "$2" == "=" ]; then
            eval "${property}=$3"
        else
            eval "echo \${${property}}"
        fi
    fi
}

new () {
    identifier="oob_$1_${RANDOM}"
    class_definition=$(declare -f $1)
    instance_definition="${identifier}${class_definition#$1}"
    echo "$instance_definition"
    echo "declare -A ${identifier}_props"
    echo -e "${identifier} ${identifier}" '$@'
}
